# Generated by Django 5.2.4 on 2025-07-26 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('buy_date', models.DateField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sell_date', models.DateField()),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ended', models.BooleanField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
