# Generated by Django 5.2.4 on 2025-07-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
