# Generated by Django 5.2.4 on 2025-07-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_registry', '0002_alter_trade_sell_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='profit',
        ),
    ]
