# Generated by Django 4.2 on 2026-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_registry', '0003_remove_trade_ended_remove_trade_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='name',
            field=models.CharField(default='TBD', max_length=100),
        ),
    ]
