# Generated by Django 4.2 on 2026-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_registry', '0004_trade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('ticker', models.CharField()),
                ('link', models.CharField()),
                ('published', models.DateTimeField()),
                ('summary', models.CharField()),
            ],
        ),
    ]
