# Generated by Django 4.2 on 2026-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_registry', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
