# Generated by Django 4.2 on 2026-02-15 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_registry', '0007_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='name',
        ),
        migrations.AlterField(
            model_name='news',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='trade_registry.ticker'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trade_registry.ticker'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
    ]
