# Generated by Django 4.2 on 2026-02-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_registry', '0008_remove_trade_name_alter_news_ticker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='ticker',
            name='last_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
